
logging:
  level:
    org.apache.http.headers: warn
    org.apache.http.wire: warn
    org.apache.http: warn
    software.amazon.awssdk: warn
  config: classpath:logcfg-dev.xml

server:
  port: 8185
  address: 0.0.0.0


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/login?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useOldAliasMetadataBehavior=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 200
      auto-commit: true
      idle-timeout: 60000
      pool-name: HikariCP
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      validation-timeout: 60000
      login-timeout: 5
      register-mbeans: true
  jpa:
    hibernate:
      ddl-auto: update
  #redis
  redis:
    redisson:
      config: |
        threads: 8
        nettyThreads: 8
        singleServerConfig:
          address: redis://127.0.0.1:6379
          password: 123456
twitter:
  clientId: aWVBTTZKV2xGSURfbVFwYzBaWWQ6MTpjaQ
  clientSecret: E7O6T7sNtK2-qFtJ1KDGedl19sOxYE8FlWfhE74cYFbVEsJ4dc
  redirectUrl: https://aitown.infinitytest.cc/
  consumerKey: 11
  consumerSecret: 11
